# Generated by Django 4.2.17 on 2025-02-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_userdetail_groups_userdetail_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usersettingsmodel',
            table='user_settings',
        ),
    ]
